spring.application.name=eventos

spring.datasource.url=jdbc:postgresql://localhost:5433/rental_db
spring.datasource.username=postgres
spring.datasource.password=aluno

spring.jpa.show-sql=true

springdoc.swagger-ui.path=/eventos/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true